# Generated by Django 4.1.1 on 2022-10-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="image_file",
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
